### ISSUE TITLE
Wrong URL in "Bonus slide"

### ISSUE THREAD

**Issue by jcarolinares** [Jesus89/slides#1]
The URL goes to:

https://jesus89.github.io/slides/

Instead of:

https://github.com/Jesus89/slides/tree/master/2016-10-Python-uControllers-and-FPGAs/examples/Python-resources

![image](https://cloud.githubusercontent.com/assets/7687624/20058045/2559d4ee-a4ef-11e6-96e0-5329b3d7c67d.png)

**Comment by Jesus89** [comment]
Right Julian!

These links are not set. Let's fix that.

**Comment by Jesus89** [comment]
Done. Now it is time to wait for github page to be updated.
